export default {
  FR: {
    DAYS: ['dimanche', 'lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi'],
    MONTHS: [
      'janvier',
      'fevrier',
      'mars',
      'avril',
      'mai',
      'juin',
      'juillet',
      'aout',
      'septembre',
      'octobre',
      'novembre',
      'decembre',
    ],
  },
  EN: {
    DAYS: ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
    MONTHS: [
      'january',
      'february',
      'march',
      'april',
      'may',
      'june',
      'july',
      'august',
      'september',
      'october',
      'november',
      'december',
    ],
  },
  PT_BR: {
    DAYS: ['domingo', 'segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado'],
    MONTHS: [
      'janeiro', 
      'fevereiro', 
      'março', 
      'abril', 
      'maio', 
      'junho', 
      'julho', 
      'agosto', 
      'setembro', 
      'outubro', 
      'novembro', 
      'dezembro',
    ],
  },
}
